version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
workflows:
  build-and-push-dev:
    jobs:
      - aws-ecr/build-and-push-image:
          context: work-counter-aws
          repo: "${APP_PREFIX}-front"
          tag: "develop"
          filters:
            branches:
              only:
                - develop
  build-and-push-prod:
    jobs:
      - aws-ecr/build-and-push-image:
          context: work-counter-aws
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${APP_PREFIX}-front"
          region: ${AWS_DEFAULT_REGION}
          tag: "latest"
          filters:
            branches:
              only:
                - master
  build-and-push-tag:
    jobs:
      - aws-ecr/build-and-push-image:
          context: work-counter-aws
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${APP_PREFIX}-front"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_TAG}"
          filters:
            tags:
              only:
                - /^update-*/
